/**
 * Shared TypeScript type definitions for CampuSync.
 *
 * These types supplement the auto-generated Supabase types in
 * src/integrations/supabase/types.ts with application-level
 * types used across components and hooks.
 *
 * Do not duplicate types that are already generated by Supabase.
 * Import generated row types from @/integrations/supabase/types.
 */

import { AttendanceStatus, UserRole } from '@/lib/constants';

/** Represents a user profile as returned from the profiles table. */
export interface Profile {
  id: string;
  email: string;
  full_name: string;
  role: UserRole;
  created_at: string;
  updated_at: string;
}

/** Represents an academic module. */
export interface Module {
  id: string;
  code: string;
  name: string;
  description: string | null;
  lecturer_id: string | null;
  attendance_threshold: number;
  created_at: string;
  updated_at: string;
}

/** Represents a teaching session belonging to a module. */
export interface Session {
  id: string;
  module_id: string;
  session_date: string;
  session_number: number;
  start_time: string;
  topic: string | null;
  created_by: string;
  created_at: string;
}

/** Represents a single attendance record. */
export interface AttendanceRecord {
  id: string;
  student_id: string;
  session_id: string;
  status: AttendanceStatus;
  marked_by: string;
  marked_at: string;
}

/** Computed attendance statistics for a student within a module. */
export interface AttendanceStats {
  total: number;
  present: number;
  late: number;
  absent: number;
  percentage: number;
  isAtRisk: boolean;
  absencesRemaining: number;
}

/** A student with their computed attendance stats for a given module. */
export interface StudentWithStats extends Profile {
  stats: AttendanceStats;
}
